### ISSUE TITLE
SAM local run Error

### ISSUE THREAD

**Issue by asyba** [ManivannanMurugavel/selenium-python-aws-lambda#3]
```
Starting google.com
Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
: WebDriverException
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 53, in lambda_handler
    driver = webdriver.Chrome(chrome_options=chrome_options)
  File "/var/task/selenium/webdriver/chrome/webdriver.py", line 68, in __init__
    self.service.start()
  File "/var/task/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


END RequestId: 32e1ecb4-3781-4c7b-8898-52a82b4c625c
REPORT RequestId: 32e1ecb4-3781-4c7b-8898-52a82b4c625c Duration: 67 ms Billed Duration: 100 ms Memory Size: 256 MB Max Memory Used: 21 MB
```

**Comment by ManivannanMurugavel** [comment]
Hi @asyba ,

Please see my medium [blog](https://medium.com/@manivannan_data/python-selenium-on-aws-lambda-b4b9de44b8e1) and do the step 2.
Check the chromedriver binary location in lambda_function.py.
